name: binder
channels:
  - conda-forge
dependencies:
  - python
  - pymc3
  - numpy
  - matplotlib
  - matplotlib.pyplot
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib